### ISSUE TITLE
Improve Functionality in navbar

### ISSUE THREAD

**Issue by Riya14-dangra** [i-ujjwaljha/E-Commerce-Website#16]
I want to make the navbar more responsive and wish to add hover effects in it

**Comment by Riya14-dangra** [comment]
> I want to make the navbar more responsive and wish to add hover effects in it

@i-ujjwaljha can you please assign this issue to me I want to work on it

**Comment by Riya14-dangra** [comment]
> Hey @i-ujjwaljha, I had made many projects with attractive and responsive nav- bars. Here is a demo for the same. Please assign this issue to me.
> 
>  WhatsApp.Video.2022-12-10.at.21.43.24.mp4

 @yashiyadav6602 Dude I have created this issue because I want to work on it

**Comment by yashiyadav6602** [comment]
@Riya14-dangra  Chill bro. May the issue get assigned to one, who can do it better. Let @i-ujjwaljha decide.

**Comment by i-ujjwaljha** [comment]
Hey, @Riya14-dangra you already contributed to a few issues, so can we let @yashiyadav6602 contribute this time?
Since you created this issue, so I will let you decide.

**Comment by Riya14-dangra** [comment]
> Hey, @Riya14-dangra you already contributed to a few issues, so can we let @yashiyadav6602 contribute this time? Since you created this issue, so I will let you decide.

I think these website is too much sufficient to work with another issue so @yashiyadav6602 please choice another section to work with or create new section as you want and  @i-ujjwaljha if you wish then assign this to me because I want to work on it

**Comment by i-ujjwaljha** [comment]
Okay @Riya14-dangra, go ahead with the issue.
