### ISSUE TITLE
Improving the ui of about section

### ISSUE THREAD

**Issue by Janhvi52** [i-ujjwaljha/E-Commerce-Website#18]
![Screenshot (80)](https://user-images.githubusercontent.com/97719669/206888806-5566e56b-4150-4538-a13f-2db67d3d0a99.png)

The font size and size of the picture is not according to the rest of the website
Can you please assign me this issue so that i can improve the ui so that it'll be in accordance with the webpage!
@i-ujjwaljha

**Comment by i-ujjwaljha** [comment]
Go ahead with the issue @Janhvi52
