### ISSUE TITLE
Add slider to testimonials section

### ISSUE THREAD

**Issue by Riya14-dangra** [i-ujjwaljha/E-Commerce-Website#25]
As if there are more than 3 testimonials so we have need to added a slider to testimonials section

**Comment by Riya14-dangra** [comment]
> As if there are more than 3 testimonials so we have need to added a slider to testimonials section

@i-ujjwaljha can you please assign this issue to me  I want to work on it under kwoc2022

**Comment by i-ujjwaljha** [comment]
work on it @Riya14-dangra
