### ISSUE TITLE
Add about section

### ISSUE THREAD

**Issue by Riya14-dangra** [i-ujjwaljha/E-Commerce-Website#3]

**Comment by Riya14-dangra** [comment]
hey @i-ujjwaljha can you please assign this issue to me under KWOC2022? I want to work on it.

**Comment by i-ujjwaljha** [comment]
go for it

**Comment by Riya14-dangra** [comment]
thank you!! should I merge it to master branch or new branch

**Comment by i-ujjwaljha** [comment]
Commit to a new branch and create a pull request.
