### ISSUE TITLE
Duplicate Product Details

### ISSUE THREAD

**Issue by donnamware** [i-ujjwaljha/E-Commerce-Website#31]
I saw that the products all have the same pricing and general description. 

![image](https://user-images.githubusercontent.com/120144035/207494151-fb124148-b900-4578-8238-9f2a1bc99faa.png)

**Comment by i-ujjwaljha** [comment]
go ahead and make the changes you think will be fine for the website @donnamware .

**Comment by donnamware** [comment]
All products have been updated. I also put an update in the code section. I hope this wasn't overkilled as I am just beginning to learn the proper protocols for GitHub. Thank you for the opportunity. 

<div class="col-4">
            <img src="images/product-1.jpg" alt="">
            <h4>Red Printed T-shirt</h4>
            <div class="rating">
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star-o" aria-hidden="true"></i>
            </div>
            <p>$50.00</p>
        </div>

        <div class="col-4">
            <img src="images/product-2.jpg" alt="">
            <h4>Casual Black Sneakers</h4>
            <div class="rating">
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star-o" aria-hidden="true"></i>
            </div>
            <p>$50.00</p>
        </div>

        <div class="col-4">
            <img src="images/product-3.jpg" alt="">
            <h4>Grey Sweatpants with Zipper</h4>
            <div class="rating">
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star-half-o" aria-hidden="true"></i>
                <i class="fa fa-star-o" aria-hidden="true"></i>
            </div>
            <p>$50.00</p>
        </div>

        <div class="col-4">
            <img src="images/product-4.jpg" alt="">
            <h4>Navy Blue Preppy Polo Shirt</h4>
            <div class="rating">
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star-o" aria-hidden="true"></i>
            </div>
            <p>$50.00</p>
        </div>
    </div>
</section>
    <h2 class="title">Latest Products</h2>
    <div class="row">
        <div class="col-3">
            <img src="images/category-1.jpg" alt="">
        </div>
        <div class="col-3">
            <img src="images/category-2.jpg" alt="">
        </div>
        <div class="col-3">
            <img src="images/category-3.jpg" alt="">
        </div>
    </div>
</div>
</div>


<div class="small-container">
    <h2 class="title">Featured Products</h2>
    <div class="row">
        <div class="col-4">
            <img src="images/product-5.jpg" alt="">
            <h4>White Fashion High Top Leather and Knit Shoe/h4>
            <div class="rating">
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star-o" aria-hidden="true"></i>
            </div>
            <p>$50.00</p>
        </div>

        <div class="col-4">
            <img src="images/product-6.jpg" alt="">
            <h4>PUMA Black Tee-Shirt with Strips</h4>
            <div class="rating">
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star-o" aria-hidden="true"></i>
            </div>
            <p>$50.00</p>
        </div>

        <div class="col-4">
            <img src="images/product-7.jpg" alt="">
            <h4>Hrx Cotton Quarter Length Trainning Socks</h4>
            <div class="rating">
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star-half-o" aria-hidden="true"></i>
                <i class="fa fa-star-o" aria-hidden="true"></i>
            </div>
            <p>$50.00</p>
        </div>

        <div class="col-4">
            <img src="Black Fossil Sports Watch" alt="">
            <h4>Red Printed T-shirt</h4>
            <div class="rating">
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star-o" aria-hidden="true"></i>
            </div>
            <p>$50.00</p>
        </div>

        <div class="col-4">
            <img src="images/product-9.jpg" alt="">
            <h4>Black Roadster Leather Band Sports Watch</h4>
            <div class="rating">
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star-o" aria-hidden="true"></i>
            </div>
            <p>$50.00</p>
        </div>

        <div class="col-4">
            <img src="images/product-10.jpg" alt="">
            <h4>Black and Red Low Top Training Shoe</h4>
            <div class="rating">
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star-o" aria-hidden="true"></i>
            </div>
            <p>$50.00</p>
        </div>

        <div class="col-4">
            <img src="images/product-11.jpg" alt="">
            <h4>Grey and White Mesh Fashion Shoe</h4>
            <div class="rating">
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star-o" aria-hidden="true"></i>
            </div>
            <p>$50.00</p>
        </div>

        <div class="col-4">
            <img src="images/product-12.jpg" alt="">
            <h4>Black Nike Sweat Pants with Draw String</h4>
            <div class="rating">
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star" aria-hidden="true"></i>
                <i class="fa fa-star-o" aria-hidden="true"></i>
            </div>
            <p>$50.00</p>
        </div>
    </div>

</div>
