### ISSUE TITLE
improving testmonials section

### ISSUE THREAD

**Issue by NiharikaSharma18** [i-ujjwaljha/E-Commerce-Website#33]
i will improve the testimonals section of ecommerce site and make it more attractive

**Comment by NiharikaSharma18** [comment]
hey! ujjwajjha can u please assign the issue

**Comment by i-ujjwaljha** [comment]
go ahead @NiharikaSharma18

**Comment by NiharikaSharma18** [comment]
Kindly review and merge the issue ujjwal sir

**Comment by NiharikaSharma18** [comment]
Sir,u haven't reviewed it yet
