### ISSUE TITLE
navbar is not fixed

### ISSUE THREAD

**Issue by almanac123** [i-ujjwaljha/E-Commerce-Website#42]
Can you assign me this under the label KWOC22

**Comment by i-ujjwaljha** [comment]
Go ahead

**Comment by almanac123** [comment]
Thanks,will do

**Comment by SomilRathore01** [comment]
Hey @i-ujjwaljha can you please assign this project to me for competing in KWOC 2022.

**Comment by i-ujjwaljha** [comment]
Try it out @SomilRathore01
