### ISSUE TITLE
Remove all Scroll bars from the Testimonials section

### ISSUE THREAD

**Issue by Avik1320** [i-ujjwaljha/E-Commerce-Website#45]
There are some **unnecessary scroll bars present in the Testimonials section**. I think if it will **remove it can enhance the UI**.
I would like to request you to assign the work to me.
![image](https://user-images.githubusercontent.com/98302991/208995627-4f8a47a5-c36f-4f2f-9d94-692e986d7b07.png)

**Comment by i-ujjwaljha** [comment]
Go ahead with the Issue @Avik1320
